In [10]:
import pandas as pd
df=pd.read_csv(r"C:\Users\kathy\Downloads\annual-enterprise-survey-2023-financial-year-provisional.csv")
df

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2023,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,930995,ANZSIC06 divisions A-S (excluding classes K633...
1,2023,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,821630,ANZSIC06 divisions A-S (excluding classes K633...
2,2023,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,84354,ANZSIC06 divisions A-S (excluding classes K633...
3,2023,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25010,ANZSIC06 divisions A-S (excluding classes K633...
4,2023,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,832964,ANZSIC06 divisions A-S (excluding classes K633...
...,...,...,...,...,...,...,...,...,...,...
50980,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H37,Quick ratio,Financial ratios,52,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
50981,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H38,Margin on sales of goods for resale,Financial ratios,40,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
50982,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H39,Return on equity,Financial ratios,12,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
50983,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H40,Return on total assets,Financial ratios,5,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."
50984,2013,Level 3,ZZ11,Food product manufacturing,Percentage,H41,Liabilities structure,Financial ratios,46,"ANZSIC06 groups C111, C112, C113, C114, C115, ..."

In [9]:
df.head()

,Year,Industry_aggregation_NZSIOC,Industry_code_NZSIOC,Industry_name_NZSIOC,Units,Variable_code,Variable_name,Variable_category,Value,Industry_code_ANZSIC06
0,2023,Level 1,99999,All industries,Dollars (millions),H01,Total income,Financial performance,930995,ANZSIC06 divisions A-S (excluding classes K633...
1,2023,Level 1,99999,All industries,Dollars (millions),H04,"Sales, government funding, grants and subsidies",Financial performance,821630,ANZSIC06 divisions A-S (excluding classes K633...
2,2023,Level 1,99999,All industries,Dollars (millions),H05,"Interest, dividends and donations",Financial performance,84354,ANZSIC06 divisions A-S (excluding classes K633...
3,2023,Level 1,99999,All industries,Dollars (millions),H07,Non-operating income,Financial performance,25010,ANZSIC06 divisions A-S (excluding classes K633...
4,2023,Level 1,99999,All industries,Dollars (millions),H08,Total expenditure,Financial performance,832964,ANZSIC06 divisions A-S (excluding classes K633...

In [ ]:
import pandas as pd

# Correct file path using a raw string
file_path = r"import pandas as pd

# Correct file path using a raw string
file_path = r"C:\Users\prana\OneDrive\Desktop\abc.xlsx"

# Load specific sheets into a dictionary of DataFrames
xls = pd.read_excel(file_path, sheet_name=['Sheet1', 'Sheet2'])

# Access individual sheets
sheet1_df = xls['Sheet1']
sheet2_df = xls['Sheet2']

# Print the content of each sheet
print("Sheet1 Content:")
print(sheet1_df)

print("\nSheet2 Content:")
print(sheet2_df).xlsx"

# Load specific sheets into a dictionary of DataFrames
xls = pd.read_excel(file_path, sheet_name=['Sheet1', 'Sheet2'])

# Access individual sheets
sheet1_df = xls['Sheet1']
sheet2_df = xls['Sheet2']

# Print the content of each sheet
print("Sheet1 Content:")
print(sheet1_df)

print("\nSheet2 Content:")
print(sheet2_df)

In [11]:
import pandas as pd

# Correct file path using a raw string
file_path = r"C:\Users\kathy\OneDrive\ë¬¸ì„œ\Book1.xlsx"

# Load specific sheets into a dictionary of DataFrames
xls = pd.read_excel(file_path, sheet_name=['Sheet1', 'Sheet2'])

# Access individual sheets
sheet1_df = xls['Sheet1']
sheet2_df = xls['Sheet2']

# Print the content of each sheet
print("Sheet1 Content:")
print(sheet1_df)

print("\nSheet2 Content:")
print(sheet2_df)

Sheet1 Content:
                 Unnamed: 0                   Unnamed: 1  \
0                      Year  Industry_aggregation_NZSIOC
1                         0                         2023
2                         1                         2023
3                         2                         2023
4                         3                         2023
5                         4                         2023
6                       ...                          ...
7                     50980                         2013
8                     50981                         2013
9                     50982                         2013
10                    50983                         2013
11                    50984                         2013
12                      NaN                          NaN
13  50985 rows Ã— 10 columns                          NaN

              Unnamed: 2            Unnamed: 3                  Unnamed: 4  \
0   Industry_code_NZSIOC  Industry_name_NZSIOC                       Units
1                Level 1                 99999              All industries
2                Level 1                 99999              All industries
3                Level 1                 99999              All industries
4                Level 1                 99999              All industries
5                Level 1                 99999              All industries
6                    ...                   ...                         ...
7                Level 3                  ZZ11  Food product manufacturing
8                Level 3                  ZZ11  Food product manufacturing
9                Level 3                  ZZ11  Food product manufacturing
10               Level 3                  ZZ11  Food product manufacturing
11               Level 3                  ZZ11  Food product manufacturing
12                   NaN                   NaN                         NaN
13                   NaN                   NaN                         NaN

            Unnamed: 5     Unnamed: 6  \
0        Variable_code  Variable_name
1   Dollars (millions)            H01
2   Dollars (millions)            H04
3   Dollars (millions)            H05
4   Dollars (millions)            H07
5   Dollars (millions)            H08
6                  ...            ...
7           Percentage            H37
8           Percentage            H38
9           Percentage            H39
10          Percentage            H40
11          Percentage            H41
12                 NaN            NaN
13                 NaN            NaN

                                         Unnamed: 7             Unnamed: 8  \
0                                 Variable_category                  Value
1                                      Total income  Financial performance
2   Sales, government funding, grants and subsidies  Financial performance
3                 Interest, dividends and donations  Financial performance
4                              Non-operating income  Financial performance
5                                 Total expenditure  Financial performance
6                                               ...                    ...
7                                       Quick ratio       Financial ratios
8               Margin on sales of goods for resale       Financial ratios
9                                  Return on equity       Financial ratios
10                           Return on total assets       Financial ratios
11                            Liabilities structure       Financial ratios
12                                              NaN                    NaN
13                                              NaN                    NaN

                Unnamed: 9                                        Unnamed: 10
0   Industry_code_ANZSIC06                                                NaN
1                   930995  ANZSIC06 divisions A-S (excluding classes K633...
2                   821630  ANZSIC06 divisions A-S (excluding classes K633...
3                    84354  ANZSIC06 divisions A-S (excluding classes K633...
4                    25010  ANZSIC06 divisions A-S (excluding classes K633...
5                   832964  ANZSIC06 divisions A-S (excluding classes K633...
6                      ...                                                ...
7                       52  ANZSIC06 groups C111, C112, C113, C114, C115, ...
8                       40  ANZSIC06 groups C111, C112, C113, C114, C115, ...
9                       12  ANZSIC06 groups C111, C112, C113, C114, C115, ...
10                       5  ANZSIC06 groups C111, C112, C113, C114, C115, ...
11                      46  ANZSIC06 groups C111, C112, C113, C114, C115, ...
12                     NaN                                                NaN
13                     NaN                                                NaN

Sheet2 Content:
                       Year Industry_aggregation_NZSIOC Industry_code_NZSIOC  \
0                         0                        2023              Level 1
1                         1                        2023              Level 1
2                         2                        2023              Level 1
3                         3                        2023              Level 1
4                         4                        2023              Level 1
5                       ...                         ...                  ...
6                     50980                        2013              Level 3
7                     50981                        2013              Level 3
8                     50982                        2013              Level 3
9                     50983                        2013              Level 3
10                    50984                        2013              Level 3
11                      NaN                         NaN                  NaN
12  50985 rows Ã— 10 columns                         NaN                  NaN

   Industry_name_NZSIOC                       Units       Variable_code  \
0                 99999              All industries  Dollars (millions)
1                 99999              All industries  Dollars (millions)
2                 99999              All industries  Dollars (millions)
3                 99999              All industries  Dollars (millions)
4                 99999              All industries  Dollars (millions)
5                   ...                         ...                 ...
6                  ZZ11  Food product manufacturing          Percentage
7                  ZZ11  Food product manufacturing          Percentage
8                  ZZ11  Food product manufacturing          Percentage
9                  ZZ11  Food product manufacturing          Percentage
10                 ZZ11  Food product manufacturing          Percentage
11                  NaN                         NaN                 NaN
12                  NaN                         NaN                 NaN

   Variable_name                                Variable_category  \
0            H01                                     Total income
1            H04  Sales, government funding, grants and subsidies
2            H05                Interest, dividends and donations
3            H07                             Non-operating income
4            H08                                Total expenditure
5            ...                                              ...
6            H37                                      Quick ratio
7            H38              Margin on sales of goods for resale
8            H39                                 Return on equity
9            H40                           Return on total assets
10           H41                            Liabilities structure
11           NaN                                              NaN
12           NaN                                              NaN

                    Value Industry_code_ANZSIC06  \
0   Financial performance                 930995
1   Financial performance                 821630
2   Financial performance                  84354
3   Financial performance                  25010
4   Financial performance                 832964
5                     ...                    ...
6        Financial ratios                     52
7        Financial ratios                     40
8        Financial ratios                     12
9        Financial ratios                      5
10       Financial ratios                     46
11                    NaN                    NaN
12                    NaN                    NaN

                                          Unnamed: 10
0   ANZSIC06 divisions A-S (excluding classes K633...
1   ANZSIC06 divisions A-S (excluding classes K633...
2   ANZSIC06 divisions A-S (excluding classes K633...
3   ANZSIC06 divisions A-S (excluding classes K633...
4   ANZSIC06 divisions A-S (excluding classes K633...
5                                                 ...
6   ANZSIC06 groups C111, C112, C113, C114, C115, ...
7   ANZSIC06 groups C111, C112, C113, C114, C115, ...
8   ANZSIC06 groups C111, C112, C113, C114, C115, ...
9   ANZSIC06 groups C111, C112, C113, C114, C115, ...
10  ANZSIC06 groups C111, C112, C113, C114, C115, ...
11                                                NaN
12                                                NaN

In [12]:
import numpy as np

In [13]:
a=np.ones(3)

In [14]:
a

array([1., 1., 1.])

In [15]:
type(a[0])

numpy.float64

In [16]:
z=np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [17]:
z.shape

(10,)

In [18]:
z.shape=(10,1)
z

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [21]:
z=np.ones(10)
type(z[0])
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [22]:
z=np.empty(3)
z

array([1., 1., 1.])

In [24]:
z=np.linspace(1,9,5)
z

array([1., 3., 5., 7., 9.])

In [26]:
z=np.array([10,20])
z

array([10, 20])